####################
# NEXUS
####################

#gradle-wrapper
#systemProp.gradle.wrapperUser=msa_dev
#systemProp.gradle.wrapperPassword=msa_dev!@

#pluginManagement credentials
#NEXUS_MAVEN_PUBLIC_URL=https://nexus.dev.k8s:31300/repository/maven-public/
#NEXUS_MAVEN_EGOV_URL=https://nexus.dev.k8s:31300/repository/maven-public-egov/
#NEXUS_USERNAME=msa_dev
#NEXUS_PASSWORD=msa_dev!@

####################
# Version
####################

#plugins
springBootVersion=2.7.18
springDependencyManagementVersion=1.0.15.RELEASE
sonarqubeVersion=4.0.0.2929

#dependencies
eGovFrameVersion=4.3.0
#onnaraCmmnVersion=2025.03.04
#prismCmmnVersion=2024.11.19
#prismBizVersion=2024.11.14

#dependencyManagement
springCloudVersion=2021.0.8
otelVersion=1.1.2

#outer architecture
opentelemetryVersion=1.2
