spring:
  config:
    import:
    - application-db.yml #local db 정보
    - optional:configserver:${config.server.host:http://localhost:8888/} #configmap
  profiles:
    active: local #default
    group:
      local:
        - saas-db-local # - kc-onnara-db-local
      dev:
        - saas-db-dev
      ops:
        - kc-onnara-db-ops

---
spring:
  config:
    activate:
      on-profile:
      - local
      - dev
      - ops
  application:
    name: iop-ci-catalog

server:
  port: 9991

system-info: catalog

info:
  app:
    name: 게시판 서비스 (${spring.profiles.active})
    description: 게시판을 이용하거나 관리하기 위한 서비스
    version: v0.0.1

feign.circuitbreaker.enabled: true

---
#H2 테스트용
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never #always
      continue-on-error: true
      data-locations:
      - classpath:init-data/data.sql
      schema-locations:
      - classpath:init-data/tables_new.sql
      
 
---
saas:
  dev:
    url: http://localhost:9991
  prod:
    url: http://localhost:9991
    
---
jwt:
  secret: mySuperSecretKeyForJWTGenerationChangeThisIsLongEnough123!
  access-expiration: 600000 #3600000        # 1시간 (밀리초)  60000  10분
  refresh-expiration: 2592000000    # 30일 (밀리초)
